import {
    BloodUnit,
    DonorRecord,
    RequestRecord,
    DonationDrive,
    Facility,
    StorageEquipment,
    AuditLog,
    DiscardLog,
    AiForecastData,
} from './types';

export const initialFacilities: Facility[] = [
    {
        id: 'fac-1',
        code: 'FAC-CBB',
        name: 'Central Blood Bank & Processing Hub',
        type: 'Central Blood Bank',
        city: 'Metropolitan Medical District',
        phone: '+1 (555) 019-2831',
        refrigeratorsCount: 6,
        freezersCount: 4,
        agitatorsCount: 3,
        status: 'Operational',
        totalUnitsInStock: 8,
        availableUnits: 6,
    },
    {
        id: 'fac-2',
        code: 'FAC-CGH',
        name: 'City General Hospital Lab',
        type: 'Hospital Lab',
        city: 'Downtown Core',
        phone: '+1 (555) 014-9922',
        refrigeratorsCount: 3,
        freezersCount: 2,
        agitatorsCount: 1,
        status: 'Operational',
        totalUnitsInStock: 4,
        availableUnits: 3,
    },
    {
        id: 'fac-3',
        code: 'FAC-STJ',
        name: 'St. Jude Trauma Center Lab',
        type: 'Hospital Lab',
        city: 'Westside Emergency Wing',
        phone: '+1 (555) 018-4411',
        refrigeratorsCount: 4,
        freezersCount: 2,
        agitatorsCount: 2,
        status: 'Operational',
        totalUnitsInStock: 3,
        availableUnits: 2,
    },
];

export const initialEquipment: StorageEquipment[] = [
    {
        id: 'eq-1',
        facilityId: 'fac-1',
        name: 'Main Cold Vault Ref-01',
        type: 'Refrigerator (2-6°C)',
        currentTempC: 3.8,
        targetTempC: 4.0,
        status: 'Normal',
        capacityUnits: 250,
        occupiedUnits: 142,
    },
    {
        id: 'eq-2',
        facilityId: 'fac-1',
        name: 'Deep Plasma Freezer FZ-01',
        type: 'Freezer (-30°C)',
        currentTempC: -29.4,
        targetTempC: -30.0,
        status: 'Normal',
        capacityUnits: 180,
        occupiedUnits: 98,
    },
    {
        id: 'eq-3',
        facilityId: 'fac-1',
        name: 'Platelet Incubator AG-01',
        type: 'Platelet Agitator (20-24°C)',
        currentTempC: 22.1,
        targetTempC: 22.0,
        status: 'Normal',
        capacityUnits: 60,
        occupiedUnits: 34,
    },
    {
        id: 'eq-4',
        facilityId: 'fac-2',
        name: 'Stat Emergency Ref-02',
        type: 'Refrigerator (2-6°C)',
        currentTempC: 4.5,
        targetTempC: 4.0,
        status: 'Normal',
        capacityUnits: 100,
        occupiedUnits: 58,
    },
    {
        id: 'eq-5',
        facilityId: 'fac-3',
        name: 'Trauma Wing Ref-03',
        type: 'Refrigerator (2-6°C)',
        currentTempC: 5.8,
        targetTempC: 4.0,
        status: 'Warning',
        capacityUnits: 120,
        occupiedUnits: 82,
    },
];

export const initialDonors: DonorRecord[] = [
    {
        id: 'dnr-1',
        donorCode: 'DNR-1001',
        fullName: 'Alexander Vance',
        bloodType: 'O-',
        age: 34,
        gender: 'Male',
        phone: '+1 (555) 234-5678',
        email: 'a.vance@example.com',
        address: '452 Pine Ave',
        lastDonationDate: '2026-08-15',
        eligibilityStatus: 'Eligible',
        totalDonationsCount: 14,
        hemoglobinGdl: 15.2,
        bloodPressure: '120/78',
        weightKg: 78,
    },
    {
        id: 'dnr-2',
        donorCode: 'DNR-1002',
        fullName: 'Elena Rostova',
        bloodType: 'A+',
        age: 29,
        gender: 'Female',
        phone: '+1 (555) 345-6789',
        email: 'elena.r@example.com',
        address: '781 Birch St',
        lastDonationDate: '2026-09-18',
        eligibilityStatus: 'Eligible',
        totalDonationsCount: 8,
        hemoglobinGdl: 13.8,
        bloodPressure: '115/72',
        weightKg: 64,
    },
    {
        id: 'dnr-3',
        donorCode: 'DNR-1003',
        fullName: 'Marcus Chen',
        bloodType: 'B+',
        age: 41,
        gender: 'Male',
        phone: '+1 (555) 456-7890',
        email: 'm.chen@example.com',
        address: '109 Oak Rd',
        lastDonationDate: '2026-07-02',
        eligibilityStatus: 'Eligible',
        totalDonationsCount: 22,
        hemoglobinGdl: 16.0,
        bloodPressure: '124/80',
        weightKg: 82,
    },
    {
        id: 'dnr-4',
        donorCode: 'DNR-1004',
        fullName: 'Sarah Jenkins',
        bloodType: 'AB+',
        age: 38,
        gender: 'Female',
        phone: '+1 (555) 567-8901',
        email: 's.jenkins@example.com',
        address: '320 Maple Dr',
        lastDonationDate: '2026-09-01',
        eligibilityStatus: 'Temporarily Deferred',
        deferralReason: 'Low Hb',
        totalDonationsCount: 5,
        hemoglobinGdl: 11.5,
        bloodPressure: '110/70',
        weightKg: 58,
    },
    {
        id: 'dnr-5',
        donorCode: 'DNR-1005',
        fullName: "David O'Connor",
        bloodType: 'O+',
        age: 46,
        gender: 'Male',
        phone: '+1 (555) 678-9012',
        email: 'doconnor@example.com',
        address: '88 West Highland',
        lastDonationDate: '2026-07-28',
        eligibilityStatus: 'Eligible',
        totalDonationsCount: 19,
        hemoglobinGdl: 14.9,
        bloodPressure: '128/82',
        weightKg: 85,
    },
];

export const initialUnits: BloodUnit[] = [
    {
        id: 'bld-1',
        unitNumber: 'BLD-2026-8901',
        bloodType: 'O-',
        component: 'Packed Red Blood Cells',
        facilityId: 'fac-1',
        facilityName: 'Central Blood Bank & Processing Hub',
        location: 'Main Cold Vault Ref-01 / Shelf A',
        temperatureZone: '2°C to 6°C',
        volumeMl: 450,
        collectionDate: '2026-09-22',
        expiryDate: '2026-10-27',
        status: 'Available',
        donorId: 'dnr-1',
        donorCode: 'DNR-1001',
        testingStatus: 'Tested & Passed',
        notes: 'Universal O- PRBC ready for emergency dispatch.',
    },
    {
        id: 'bld-2',
        unitNumber: 'BLD-2026-8902',
        bloodType: 'O-',
        component: 'Packed Red Blood Cells',
        facilityId: 'fac-3',
        facilityName: 'St. Jude Trauma Center Lab',
        location: 'Trauma Wing Ref-03 / Shelf 1',
        temperatureZone: '2°C to 6°C',
        volumeMl: 450,
        collectionDate: '2026-08-30',
        expiryDate: '2026-10-04',
        status: 'Available',
        donorId: 'dnr-1',
        donorCode: 'DNR-1001',
        testingStatus: 'Tested & Passed',
        notes: 'URGENT: Expiring soon!',
    },
    {
        id: 'bld-3',
        unitNumber: 'BLD-2026-8903',
        bloodType: 'O-',
        component: 'Fresh Frozen Plasma',
        facilityId: 'fac-1',
        facilityName: 'Central Blood Bank & Processing Hub',
        location: 'Deep Plasma Freezer FZ-01',
        temperatureZone: '-30°C',
        volumeMl: 250,
        collectionDate: '2026-08-20',
        expiryDate: '2027-08-20',
        status: 'Available',
        donorId: 'dnr-1',
        donorCode: 'DNR-1001',
        testingStatus: 'Tested & Passed',
    },
    {
        id: 'bld-4',
        unitNumber: 'BLD-2026-8904',
        bloodType: 'A+',
        component: 'Packed Red Blood Cells',
        facilityId: 'fac-1',
        facilityName: 'Central Blood Bank & Processing Hub',
        location: 'Main Cold Vault Ref-01 / Shelf B',
        temperatureZone: '2°C to 6°C',
        volumeMl: 450,
        collectionDate: '2026-09-27',
        expiryDate: '2026-11-01',
        status: 'Available',
        donorId: 'dnr-2',
        donorCode: 'DNR-1002',
        testingStatus: 'Tested & Passed',
    },
    {
        id: 'bld-5',
        unitNumber: 'BLD-2026-8905',
        bloodType: 'A+',
        component: 'Platelets',
        facilityId: 'fac-1',
        facilityName: 'Central Blood Bank & Processing Hub',
        location: 'Platelet Incubator AG-01',
        temperatureZone: '20-24°C',
        volumeMl: 300,
        collectionDate: '2026-09-29',
        expiryDate: '2026-10-04',
        status: 'Available',
        donorId: 'dnr-2',
        donorCode: 'DNR-1002',
        testingStatus: 'Tested & Passed',
    },
    {
        id: 'bld-6',
        unitNumber: 'BLD-2026-8906',
        bloodType: 'A+',
        component: 'Whole Blood',
        facilityId: 'fac-2',
        facilityName: 'City General Hospital Lab',
        location: 'Stat Emergency Ref-02',
        temperatureZone: '2°C to 6°C',
        volumeMl: 500,
        collectionDate: '2026-09-18',
        expiryDate: '2026-10-23',
        status: 'Cross-Matched',
        donorId: 'dnr-2',
        donorCode: 'DNR-1002',
        testingStatus: 'Tested & Passed',
    },
    {
        id: 'bld-7',
        unitNumber: 'BLD-2026-8907',
        bloodType: 'B+',
        component: 'Packed Red Blood Cells',
        facilityId: 'fac-1',
        facilityName: 'Central Blood Bank & Processing Hub',
        location: 'Main Cold Vault Ref-01 / Shelf C',
        temperatureZone: '2°C to 6°C',
        volumeMl: 450,
        collectionDate: '2026-09-24',
        expiryDate: '2026-10-29',
        status: 'Available',
        donorId: 'dnr-3',
        donorCode: 'DNR-1003',
        testingStatus: 'Tested & Passed',
    },
    {
        id: 'bld-8',
        unitNumber: 'BLD-2026-8909',
        bloodType: 'AB+',
        component: 'Fresh Frozen Plasma',
        facilityId: 'fac-1',
        facilityName: 'Central Blood Bank & Processing Hub',
        location: 'Deep Plasma Freezer FZ-01',
        temperatureZone: '-30°C',
        volumeMl: 250,
        collectionDate: '2026-09-12',
        expiryDate: '2027-09-12',
        status: 'Available',
        donorId: 'dnr-4',
        donorCode: 'DNR-1004',
        testingStatus: 'Tested & Passed',
    },
];

export const initialRequests: RequestRecord[] = [
    {
        id: 'req-1',
        requestCode: 'REQ-4091',
        hospitalName: 'St. Jude Trauma Center - ER Bay 3',
        patientName: 'Jonathan Hayes',
        patientAge: 48,
        patientGender: 'Male',
        requiredBloodType: 'O-',
        component: 'Packed Red Blood Cells',
        unitsRequested: 2,
        unitsAssigned: ['bld-1'],
        urgency: 'Emergency (Stat)',
        status: 'Cross-Matched',
        requestDate: '2026-10-02 13:45',
        requiredByDate: '2026-10-02 15:30',
        notes: 'Massive transfusion protocol activated.',
    },
    {
        id: 'req-2',
        requestCode: 'REQ-4092',
        hospitalName: 'City General Surgical ICU',
        patientName: 'Beatrice Lawson',
        patientAge: 62,
        patientGender: 'Female',
        requiredBloodType: 'A+',
        component: 'Packed Red Blood Cells',
        unitsRequested: 1,
        unitsAssigned: ['bld-4'],
        urgency: 'Urgent',
        status: 'Pending',
        requestDate: '2026-10-02 11:20',
        requiredByDate: '2026-10-03 09:00',
        notes: 'Post-op cardiac bypass support.',
    },
];

export const initialDrives: DonationDrive[] = [
    {
        id: 'drv-1',
        driveCode: 'DRV-2026-01',
        name: 'Spring Corporate Campus Blood Drive',
        organizer: 'Tech Park Health Association',
        location: 'Grand Ballroom, Innovation Tower',
        startDate: '2026-10-05',
        endDate: '2026-10-06',
        targetUnits: 120,
        collectedUnits: 0,
        registeredDonorsCount: 84,
        status: 'Scheduled',
        facilityId: 'fac-1',
    },
    {
        id: 'drv-2',
        driveCode: 'DRV-2026-02',
        name: 'University Student Union Donor Drive',
        organizer: 'Red Cross Student Chapter',
        location: 'Student Activity Hall',
        startDate: '2026-10-01',
        endDate: '2026-10-03',
        targetUnits: 90,
        collectedUnits: 42,
        registeredDonorsCount: 65,
        status: 'Active',
        facilityId: 'fac-2',
    },
];

export const initialAuditLogs: AuditLog[] = [
    {
        id: 'log-1',
        timestamp: '2026-10-02 13:48:12',
        userStaff: 'Dr. Sarah Lin (Lab Director)',
        action: 'Cross-Match Executed',
        entityType: 'Request',
        entityId: 'REQ-4091',
        details:
            'Electronic cross-match verified between Recipient (O-) and Unit BLD-2026-8901 (O- PRBC). Result: COMPATIBLE.',
        digitalSignatureHash: '0x9b3f4a21e78c9012',
    },
    {
        id: 'log-2',
        timestamp: '2026-10-02 11:25:04',
        userStaff: 'James Miller (Technician)',
        action: 'Blood Unit Intake Registered',
        entityType: 'Inventory',
        entityId: 'BLD-2026-8910',
        details:
            'Intake registration completed for AB+ PRBC unit collected from Donor DNR-1004.',
        digitalSignatureHash: '0x4c1e82a90f3177b4',
    },
];

export const initialDiscardLogs: DiscardLog[] = [
    {
        id: 'dsc-1',
        unitNumber: 'BLD-2026-8840',
        bloodType: 'A+',
        component: 'Packed Red Blood Cells',
        discardDate: '2026-09-28',
        reason: 'Expired',
        performedBy: 'James Miller (Lab Tech)',
        facilityName: 'Central Blood Bank & Processing Hub',
    },
];

export const initialAiData: AiForecastData = {
    generatedAt: new Date().toISOString(),
    confidenceScore: 0.94,
    forecastingTable: [
        {
            bloodType: 'O-',
            currentStock: 3,
            projected14DayDemand: 14,
            projectedNetBalance: -11,
            status: 'Critical Deficit',
        },
        {
            bloodType: 'O+',
            currentStock: 8,
            projected14DayDemand: 28,
            projectedNetBalance: -20,
            status: 'Critical Deficit',
        },
        {
            bloodType: 'A+',
            currentStock: 12,
            projected14DayDemand: 22,
            projectedNetBalance: -10,
            status: 'Moderate Shortage',
        },
        {
            bloodType: 'A-',
            currentStock: 4,
            projected14DayDemand: 8,
            projectedNetBalance: -4,
            status: 'Moderate Shortage',
        },
        {
            bloodType: 'B+',
            currentStock: 9,
            projected14DayDemand: 16,
            projectedNetBalance: -7,
            status: 'Moderate Shortage',
        },
        {
            bloodType: 'B-',
            currentStock: 3,
            projected14DayDemand: 5,
            projectedNetBalance: -2,
            status: 'Balanced',
        },
        {
            bloodType: 'AB+',
            currentStock: 6,
            projected14DayDemand: 7,
            projectedNetBalance: -1,
            status: 'Balanced',
        },
        {
            bloodType: 'AB-',
            currentStock: 2,
            projected14DayDemand: 3,
            projectedNetBalance: -1,
            status: 'Balanced',
        },
    ],
    expiringRiskUnitsCount: 2,
    expiringUnitsList: [
        { unit: initialUnits[1], daysRemaining: 2 },
        { unit: initialUnits[4], daysRemaining: 2 },
    ],
    recommendations: [
        {
            id: 'rec-1',
            priority: 'High',
            category: 'Urgent Donation Drive',
            text: 'Urgent demand shortfall detected for O- blood. Projected 14-day shortage of 11 units. Schedule targeted donor campaign immediately.',
        },
        {
            id: 'rec-2',
            priority: 'High',
            category: 'Stock Redistribution',
            text: 'Unit BLD-2026-8902 (O- PRBC) expires in 2 days at St. Jude Trauma Center Lab. Recommend priority dispatch to high-volume trauma hospital.',
        },
    ],
};
